name: Build

on: [push, pull_request]

jobs:
  xenctrl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]

    steps:
      - name: Install Xen headers and libraries
        run: sudo apt-get install -y libxen-dev
      - name: Install stable toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions/checkout@v1
      - name: Build crate
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy xen
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Install stable toolchain with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - uses: actions/checkout@v1
      - name: Rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
