name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - name: Install stable toolchain with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - uses: actions/checkout@v1

      - name: Rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Xen headers and libraries
        run: sudo apt-get install -y libxen-dev

      - name: Install stable toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions/checkout@v1

      - name: Build crate
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  publish:
    needs: [format, build]
    runs-on: ubuntu-20.04

    # publish on crates.io
    # only if push on master, and tag is 'v*'
    # this should be triggered by cargo release, which creates a new tag and pushes to the repo
    # cargo release --no-dev-version --skip-publish minor
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Install Xen headers and libraries
        run: sudo apt-get install -y libxen-dev

      - uses: actions/checkout@v1

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Publish
        shell: bash
        run: |
          cargo publish --token ${{ secrets.CRATES_TOKEN }}

